from distutils.core import setup

setup(
        name='SdaDashboard',
        version='',
        packages=['build.lib.build.lib.build.lib.build.lib.mmredes',
                  'build.lib.build.lib.build.lib.build.lib.mmredes.com',
                  'build.lib.build.lib.build.lib.build.lib.mmredes.com.sda',
                  'build.lib.build.lib.build.lib.build.lib.mmredes.com.sda.emailing',
                  'build.lib.build.lib.build.lib.build.lib.mmredes.com.sda.dashboard',
                  'build.lib.build.lib.build.lib.build.lib.mmredes.com.sda.dashboard.dao',
                  'build.lib.build.lib.build.lib.build.lib.mmredes.com.sda.dashboard.test',
                  'build.lib.build.lib.build.lib.build.lib.mmredes.com.sda.dashboard.management',
                  'build.lib.build.lib.build.lib.build.lib.mmredes.com.sda.dashboard.repository',
                  'build.lib.build.lib.build.lib.mmredes', 'build.lib.build.lib.build.lib.mmredes.com',
                  'build.lib.build.lib.build.lib.mmredes.com.sda',
                  'build.lib.build.lib.build.lib.mmredes.com.sda.utils',
                  'build.lib.build.lib.build.lib.mmredes.com.sda.emailing',
                  'build.lib.build.lib.build.lib.mmredes.com.sda.dashboard',
                  'build.lib.build.lib.build.lib.mmredes.com.sda.dashboard.dao',
                  'build.lib.build.lib.build.lib.mmredes.com.sda.dashboard.test',
                  'build.lib.build.lib.build.lib.mmredes.com.sda.dashboard.management',
                  'build.lib.build.lib.build.lib.mmredes.com.sda.dashboard.repository', 'build.lib.build.lib.mmredes',
                  'build.lib.build.lib.mmredes.com', 'build.lib.build.lib.mmredes.com.sda',
                  'build.lib.build.lib.mmredes.com.sda.utils', 'build.lib.build.lib.mmredes.com.sda.emailing',
                  'build.lib.build.lib.mmredes.com.sda.dashboard', 'build.lib.build.lib.mmredes.com.sda.dashboard.dao',
                  'build.lib.build.lib.mmredes.com.sda.dashboard.test',
                  'build.lib.build.lib.mmredes.com.sda.dashboard.management',
                  'build.lib.build.lib.mmredes.com.sda.dashboard.repository', 'build.lib.mmredes',
                  'build.lib.mmredes.com', 'build.lib.mmredes.com.sda', 'build.lib.mmredes.com.sda.utils',
                  'build.lib.mmredes.com.sda.emailing', 'build.lib.mmredes.com.sda.dashboard',
                  'build.lib.mmredes.com.sda.dashboard.dao', 'build.lib.mmredes.com.sda.dashboard.test',
                  'build.lib.mmredes.com.sda.dashboard.resource',
                  'build.lib.mmredes.com.sda.dashboard.resource.template',
                  'build.lib.mmredes.com.sda.dashboard.management', 'build.lib.mmredes.com.sda.dashboard.repository',
                  'mmredes', 'mmredes.com', 'mmredes.com.sda', 'mmredes.com.sda.web', 'mmredes.com.sda.web.server',
                  'mmredes.com.sda.utils', 'mmredes.com.sda.emailing', 'mmredes.com.sda.dashboard',
                  'mmredes.com.sda.dashboard.dao', 'mmredes.com.sda.dashboard.dao.dto',
                  'mmredes.com.sda.dashboard.test', 'mmredes.com.sda.dashboard.resource',
                  'mmredes.com.sda.dashboard.resource.template', 'mmredes.com.sda.dashboard.management',
                  'mmredes.com.sda.dashboard.repository'],
        url='',
        license='',
        author='Rafael',
        author_email='',
        description='',
        include_package_data=True,
        package_data={
            # If any package contains *.txt files, include them:
            '': ['*.cfg', '*.html', '*.conf'],
        }
)
